[project]
authors = ["dhk1349 <dhk1349@snu.ac.kr>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "llm_executer"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"

[pypi-dependencies]
openai = ">=1.60.0, <2"
pillow = ">=11.1.0, <12"
matplotlib = ">=3.10.0, <4"
numpy = ">=2.2.2, <3"
